---
- name: Enable Nginx from Amazon Linux Extras
  ansible.builtin.command: amazon-linux-extras enable nginx1
  changed_when: false 

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
    update_cache: true

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy web page
  ansible.builtin.copy:
    src: index.html 
    dest: /usr/share/nginx/html/index.html
    mode: '0644'
  notify: Restart Nginx