---
- name: Configure Web Server
  hosts: web
  become: true

  tasks:

    - name: Enable Nginx from amazon-linux-extras
      command: amazon-linux-extras enable nginx1

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy web page
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted